// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1inrlHO4lPkODlrxLQH4o0xQcXSq4xnU',
    appId: '1:816988382875:web:331072e9dc360b1c70483e',
    messagingSenderId: '816988382875',
    projectId: 'cobafirebase-4375b',
    authDomain: 'cobafirebase-4375b.firebaseapp.com',
    storageBucket: 'cobafirebase-4375b.appspot.com',
    measurementId: 'G-34TFVZMNQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAguCxwJjQVSfY6Pd5t-tXfHNkw5yGBKpI',
    appId: '1:816988382875:android:1b1c862d09df5db570483e',
    messagingSenderId: '816988382875',
    projectId: 'cobafirebase-4375b',
    storageBucket: 'cobafirebase-4375b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8zHcB271PJz0_6Y06xx5GQ1Jjc3P4XXc',
    appId: '1:816988382875:ios:53e2812a8602627070483e',
    messagingSenderId: '816988382875',
    projectId: 'cobafirebase-4375b',
    storageBucket: 'cobafirebase-4375b.appspot.com',
    iosClientId: '816988382875-bektcb4nc0gv3iuti20pu2jm6h0smijf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8zHcB271PJz0_6Y06xx5GQ1Jjc3P4XXc',
    appId: '1:816988382875:ios:53e2812a8602627070483e',
    messagingSenderId: '816988382875',
    projectId: 'cobafirebase-4375b',
    storageBucket: 'cobafirebase-4375b.appspot.com',
    iosClientId: '816988382875-bektcb4nc0gv3iuti20pu2jm6h0smijf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseauth',
  );
}
